clock_offset_map:
- 95
- 96
clock_set_map:
- 89
- 79
- 69
- 59
controller_input_port: Launchpad X:Launchpad X LPX MIDI In 20:1
controller_output_port: Launchpad X:Launchpad X LPX MIDI In 20:1
drumpad_input_map:
- 81
- 82
- 83
- 84
- 71
- 72
- 73
- 74
- 61
- 62
- 63
- 64
- 51
- 52
- 53
- 54
drumpad_multiplier_map:
- 69
- 59
- 49
- 39
- 29
- 19
input_channel: 0
led_config:
  led_channel: 0
  led_clock: true
  led_color_mode: true
  led_colors:
  - 15
  - 30
  - 45
  - 60
  - 75
  - 90
  - 105
  - 120
nof_displayed_tracks: 4
nof_steps: 16
nof_tracks: 8
note_input_map:
- 81
- 82
- 83
- 84
- 85
- 86
- 87
- 88
- 71
- 72
- 73
- 74
- 75
- 76
- 77
- 78
- 61
- 62
- 63
- 64
- 65
- 66
- 67
- 68
- 51
- 52
- 53
- 54
- 55
- 56
- 57
- 58
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
note_mode: toggle
output_channel: 15
track_controls_map:
  mute:
  - 79
  - 59
  - 39
  - 19
  solo:
  - 89
  - 69
  - 49
  - 29
track_mode: select_tracks
track_select_map:
- 91
- 92
track_select_mode: arrows
view_select_map:
- 93
- 94
views:
- drumpad
- velocity
- clock_set
